SiteConfig:
  extensions:
    - SiteConfig_GoogleAnalytics
Page:
  extensions:
    - IQSEO_Page
Page_Controller:
  extensions:
    - IQSEO_Page_Controller
LeftAndMain:
  extra_requirements_css:
    - iq-seo/css/cms/leftandmainadditions.css
  extra_requirements_javascript:
    - iq-seo/cms/javascript/leftandmainadditions.js